"use strict";

angular.module("app", [
  "ngAnimate",
  "ngCookies",
  "ngResource",
  "ngSanitize",
  "ngTouch",
  "ngStorage",
  "ui.router",
  "ui.bootstrap",
  "ui.load",
  "ui.jq",
  "ui.validate",
  "oc.lazyLoad",
  "angular-google-analytics",
  "pascalprecht.translate",
  "utility",
  "toaster",
  "cgBusy",
  "xeditable",
  "valid-password",
  "ngDialog",
  "ip-utility",
  "ui.bootstrap.datetimepicker",
  //    'pdf',
  "chartjs.directive",
  "infinite-scroll",
  "angucomplete-alt",
  "ngInputModified",
]);
